// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirQualityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209101435_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AirQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AQI")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "aqi");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "county");

                    b.Property<double?>("PM25")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "pm2.5");

                    b.Property<double?>("PM25Avg")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "pm2.5_avg");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "sitename");

                    b.HasKey("Id");

                    b.ToTable("AirQuality");
                });
#pragma warning restore 612, 618
        }
    }
}
