// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirQualityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209112634_ReCreateDB")]
    partial class ReCreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AirQualityAPI.Models.AirQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AQI")
                        .HasColumnType("TEXT");

                    b.Property<string>("CO")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("NO2")
                        .HasColumnType("TEXT");

                    b.Property<string>("O3")
                        .HasColumnType("TEXT");

                    b.Property<string>("O3_8hr")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM10")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM10Avg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM25")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM25Avg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SO2")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AirQuality");
                });
#pragma warning restore 612, 618
        }
    }
}
