// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirQualityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209113125_RebuildAirTable")]
    partial class RebuildAirTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AirQualityAPI.Models.AirQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AQI")
                        .HasColumnType("TEXT");

                    b.Property<string>("CO")
                        .HasColumnType("TEXT");

                    b.Property<string>("CO_8hr")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("NO")
                        .HasColumnType("TEXT");

                    b.Property<string>("NO2")
                        .HasColumnType("TEXT");

                    b.Property<string>("NOX")
                        .HasColumnType("TEXT");

                    b.Property<string>("O3")
                        .HasColumnType("TEXT");

                    b.Property<string>("O3_8hr")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM10")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM10_Avg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PM25")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pm2.5");

                    b.Property<string>("PM25_Avg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pollutant")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTime")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "publishtime");

                    b.Property<string>("SO2")
                        .HasColumnType("TEXT");

                    b.Property<string>("SO2_Avg")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wind_Direc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wind_Speed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AirQuality");
                });
#pragma warning restore 612, 618
        }
    }
}
