// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirQualityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209113752_Rebuild_Air_Model")]
    partial class Rebuild_Air_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AirQualityAPI.Models.AirQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AQI")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "aqi");

                    b.Property<string>("CO")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "co");

                    b.Property<string>("CO_8hr")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "co_8hr");

                    b.Property<string>("County")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "county");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "latitude");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "longitude");

                    b.Property<string>("NO")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "no");

                    b.Property<string>("NO2")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "no2");

                    b.Property<string>("NOX")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nox");

                    b.Property<string>("O3")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "o3");

                    b.Property<string>("O3_8hr")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "o3_8hr");

                    b.Property<string>("PM10")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pm10");

                    b.Property<string>("PM10Avg")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pm10_avg");

                    b.Property<string>("PM25")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pm2.5");

                    b.Property<string>("PM25Avg")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pm2.5_avg");

                    b.Property<string>("Pollutant")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pollutant");

                    b.Property<string>("PublishTime")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "publishtime");

                    b.Property<string>("SO2")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "so2");

                    b.Property<string>("SO2Avg")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "so2_avg");

                    b.Property<string>("SiteID")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "siteid");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "sitename");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("WindDirec")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "wind_direc");

                    b.Property<string>("WindSpeed")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "wind_speed");

                    b.HasKey("Id");

                    b.ToTable("AirQuality");
                });
#pragma warning restore 612, 618
        }
    }
}
